apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-toleration
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "exclusive"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
