apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaSet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadate:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
